aliases:
  - &ResponseHeader
    Access-Control-Allow-Origin: "*"
  - &requestRules:
    Cookie: "@123.sogou.com" # Cookie 的获取为异步，所以赞不支持 @
    Host: "@" # 取当前请求的 hostname
    Origin: "@" # 取当前请求 url
    Referer: "@" # 取当前请求 url
Cookie:
    "@123.sogou.com" # 取 123.sogou.com 域下 Cookie 复制到当前打开的 url 下，注意：不能保证完全同步
hosts:
 beta:
  # beta
  - 127.0.0.1:8088 *.dh.123.sogou.com,*.sogou.com
 dev:
  # dev
  - 127.0.0.1 *.dh.123.sogou.com,dh.123.sogou.com,123.sogou.com,*.sogou.com,*.hao123.com
rewriteUrls:
  dev:
    - matchUrl: http://123.sogou.com/*
      rules:
      - http://123.sogou.com/destination/productList.do* http://searchtouch.qunar.com/destination/productList.do* xxxx
      - match: http://123.sogou.com/queryData/searchCommentList.do*
        replace: http://searchtouch.qunar.com/queryData/searchCommentList.do*
        title: xxxx
      - match: http://searchtouch.qunar.com/*
        responseRules:
          <<: *ResponseHeader
        requestRules:
        # on: true
      - http://123.sogou.com/stat.gif* http://searchtouch.qunar.com/stat.gif*
      - http://123.sogou.com/queryData/searchSightDetail.do* http://search.qunar.com/queryData/searchSightDetail.do*
      # on: false
# ${var} is not valid yaml sytax
host:
  dev: http://123.sogou.com/
  beta: http://123.sogou.com/
  prod: http://123.sogou.com/
baseUrl:
  dev: ${host}index.html 
  beta: ${host}index.html
  prod: ${host}index.html
baseUrlQreact:
  dev: ${host}qreact.html 
  beta: ${host}qreact.html
  prod: ${host}qreact.html
urls:
  - 首页 ${baseUrl}
  - 首页2 ${baseUrlQreact}
isMobile: true